### ISSUE TITLE
Automatic mapping of pImpl functions

### ISSUE THREAD

**Issue by leongor** [oliora/samples#1]
@oliora Great sample - kudos! I was looking for some pImpl automation and your solution seems to be most elegant and compact.
I'm wondering if it's possible to eliminate Base to Impl function mapping?
As I understand if I have Base::myFunc, I still need to write something like:
`void Base::myFunc() { pImpl->myFunc(); }`
Maybe instead of function mapping we can use `std::function<void()> myFunc` member and implicitly construct it by `myFunc(std::bind( &Impl::myFunc, *pImpl))` ?
It'll be great to get rid of functions mapping especially when there are many of them.

**Comment by oliora** [comment]
Hi Leonid,
Yes you still meed to manually write proxy functions. If you don't want to then probably you should give a try to some reflection library like e.g. [Boost Reflect](http://bytemaster.github.io/boost_reflect/index.html).

I personally would not use `std::function` as a method approach because it needs almost the same amount of code resulting to an ugly and heavy class with sometimes strange behaviour (think about assigning to/from methods). Regardless, note that `std::bind` makes a copy of args so you need to use either `std::ref(*pImpl)` or `pImpl.get()` (not sure about second one) instead of `*pImpl`.

**Comment by leongor** [comment]
@oliora Thanks for the prompt answer.
Sure std::ref is needed - thanks for pointing it out. Still seems reasonable solution for me.
I'll take a look on Boost.Reflect too.
