### ISSUE TITLE
Const not enforced for unique_impl_ptr

### ISSUE THREAD

**Issue by JanPlitzkow** [oliora/samples#5]
Hi,

nice job and thanks for your work and your explanation on your blog!

However enforcing constness for methods in the private implementation seems not to work for `unique_impl_ptr`.

Consider the following example code for `impl_ptr` where everything behaves as expected:
```
class myClass
{
	myClass() :	impl_(spimpl::make_impl<myPimpl>()) {};
	void ConstFunction() const;

private:
	class myPimpl;
	spimpl::impl_ptr<myPimpl> impl_;
};

class myClass::myPimpl
{
public:
	int x_;
};

void myClass::ConstFunction() const
{
	std::cout << impl_->x_ << std::endl; // ok
	impl_->x_ = 5; // fails as expected
}
```
Using gcc I get the error `assigment of member "myClass::myPimpl::x_" in read-only object` as expected. However if I switch towards a `unique_impl_ptr`, the error is not thrown anymore:

```
class myClass
{
    myClass() :    impl_(spimpl::make_unique_impl<myPimpl>()) {};
    void ConstFunction() const;

private:
    class myPimpl;
    spimpl::unique_impl_ptr<myPimpl> impl_;
};

class myClass::myPimpl
{
public:
    int x_;
};

void myClass::ConstFunction() const
{
    std::cout << impl_->x_ << std::endl; // ok
    impl_->x_ = 5; // should fail
}
```

**Comment by vitakot** [comment]
As stated in the previous comment, the implementation is still not const correct :(

**Comment by oliora** [comment]
The problem is that `spimpl::unique_impl_ptr` is just an alias to `std::unique_ptr` (that's described in my article) which does not enforce constness as one was made to mimic standard pointer behavior.

I might get time and implement `spimpl::unique_impl_ptr` from scratch (as I did for `spimpl::impl_ptr`) to give it const correctness but I can't promise any time when it will happen. If you need it soon then you can implement it by yourself and send me PR. The implementation is straight forward: copy `spimpl::impl_ptr` and remove everything related to copying.
